### ISSUE TITLE
创建角色卡，点确定没有任何反应

### ISSUE THREAD

**Issue by marisarbq** [SunskyXH/DND-tools#1]
填好了信息，然后点”确定“不行，也没有报错。是我步骤不对吗？

**Comment by SunskyXH** [comment]
嗷嗷 这个是因为建卡需求还没有设计完，点击确定按钮是没有触发事件的，这几天忙着准备期末考试所以可能要等到寒假才能填坑了😊

**Comment by SunskyXH** [comment]
这个是因为建卡的需求还没设计好。。页面还没写完所以确定按钮是不会触发事件的 而且最近忙着准备考试，要到寒假才能填坑。。😊
